const translations = {
            en: {
                disconnected: 'Disconnected',
                connected: 'Connected',
                scanning: 'Scanning...',
                start: 'Start',
                newScramble: 'New Scramble',
                settings: 'Settings',
                scramble: 'Scramble',
                timer: 'Timer',
                inspection: 'Inspection',
                solve: 'Solve',
                ao5: 'Ao5',
                ao12: 'Ao12',
                ao100: 'Ao100',
                best: 'Best',
                average: 'Average',
                current: 'Current',
                moves: 'moves',
                cross: 'Cross',
                f2l: 'F2L',
                oll: 'OLL',
                pll: 'PLL',
                crossTime: 'Cross Time',
                f2lTime: 'F2L Time',
                f2lPairs: 'F2L Pairs',
                ollTime: 'OLL Time',
                ollCase: 'OLL Case',
                ollRecognition: 'OLL Recognition',
                pllTime: 'PLL Time',
                pllCase: 'PLL Case',
                recognitionTime: 'Recognition',
                algorithm: 'Algorithm',
                good: 'Good',
                average: 'Average',
                slow: 'Slow',
                ready: 'Ready - Make a move!',
                dnf: 'DNF',
                plus2: '+2',
                history: 'History',
                export: 'Export',
                delete: 'Delete',
                confirmDelete: 'Confirm Delete',
                cancel: 'Cancel',
                save: 'Save',
                inspectionTime: 'Inspection Time',
                soundEnabled: 'Sound Enabled',
                pressSpace: 'Press',
                pressSpace2: 'to start/stop',
                pressEnter: 'for new scramble',
                controls: 'Controls',
                sessionStats: 'Session Statistics',
                bluetoothCube: 'Bluetooth Cube',
                coachDashboard: 'Coach Dashboard',
                cfopAnalysis: 'CFOP Analysis',
                lastSolveDetails: 'Last Solve Details',
                solveHistory: 'Solve History',
                scanForCubes: 'Scan for Cubes',
                inspectionSec: 'Inspection Time (seconds)',
                timerSound: 'Timer Sound',
                time: 'Time',
                scramble: 'Scramble',
                penalty: 'Penalty',
                date: 'Date',
                solves: 'Solves',
                totalOStepTime: 'Total O-Step Time',
                crossSolution: 'Cross Solution',
                f2lPairsInserted: 'F2L Pairs Inserted',
                totalPStepTime: 'Total P-Step Time',
                pllCase: 'PLL Case',
                recognitionTime: 'Recognition Time'
            },
            zh: {
                disconnected: '未连接',
                connected: '已连接',
                scanning: '扫描中...',
                start: '开始',
                newScramble: '新打乱',
                settings: '设置',
                scramble: '打乱',
                timer: '计时器',
                inspection: '观察',
                solve: '还原',
                ao5: '5次平均',
                ao12: '12次平均',
                ao100: '100次平均',
                best: '最佳',
                average: '平均',
                current: '当前',
                moves: '步',
                cross: '十字',
                f2l: 'F2L',
                oll: 'OLL',
                pll: 'PLL',
                crossTime: '十字时间',
                f2lTime: 'F2L时间',
                f2lPairs: 'F2L对',
                ollTime: 'OLL时间',
                ollCase: 'OLL情况',
                ollRecognition: 'OLL识别',
                pllTime: 'PLL时间',
                pllCase: 'PLL情况',
                recognitionTime: '识别时间',
                algorithm: '算法',
                good: '优秀',
                average: '一般',
                slow: '较慢',
                ready: '准备 - 动手！',
                dnf: 'DNF',
                plus2: '+2',
                history: '历史',
                export: '导出',
                delete: '删除',
                confirmDelete: '确认删除',
                cancel: '取消',
                save: '保存',
                inspectionTime: '观察时间',
                soundEnabled: '开启声音',
                pressSpace: '按',
                pressSpace2: '空格键开始/停止',
                pressEnter: '获取新打乱',
                controls: '控制',
                sessionStats: '统计',
                bluetoothCube: '蓝牙魔方',
                coachDashboard: '教练面板',
                cfopAnalysis: 'CFOP分析',
                lastSolveDetails: '上次还原详情',
                solveHistory: '历史记录',
                scanForCubes: '扫描魔方',
                inspectionSec: '观察时间（秒）',
                timerSound: '计时器声音',
                time: '时间',
                scramble: '打乱',
                penalty: '罚时',
                date: '日期',
                solves: '还原次数',
                totalOStepTime: 'O步总时间',
                crossSolution: '十字解法',
                f2lPairsInserted: 'F2L对插入',
                totalPStepTime: 'P步总时间',
                pllCase: 'PLL情况',
                recognitionTime: '识别时间'
            },
            ja: {
                disconnected: '未接続',
                connected: '接続済み',
                scanning: 'スキャン中...',
                start: 'スタート',
                newScramble: '新しいスクランブル',
                settings: '設定',
                scramble: 'スクランブル',
                timer: 'タイマー',
                inspection: 'インスペクション',
                solve: '解法',
                ao5: 'ao5',
                ao12: 'ao12',
                ao100: 'ao100',
                best: 'ベスト',
                average: '平均',
                current: '現在',
                moves: '手',
                cross: 'クロス',
                f2l: 'F2L',
                oll: 'OLL',
                pll: 'PLL',
                crossTime: 'クロスタイム',
                f2lTime: 'F2Lタイム',
                f2lPairs: 'F2Lペア',
                ollTime: 'OLLタイム',
                ollCase: 'OLLケース',
                ollRecognition: 'OLL認識',
                pllTime: 'PLLタイム',
                pllCase: 'PLLケース',
                recognitionTime: '認識時間',
                algorithm: 'アルゴリズム',
                good: '良い',
                average: '普通',
                slow: '遅い',
                ready: '準備 - 始め！',
                dnf: 'DNF',
                plus2: '+2',
                history: '履歴',
                export: 'エクスポート',
                delete: '削除',
                confirmDelete: '削除確認',
                cancel: 'キャンセル',
                save: '保存',
                inspectionTime: 'インスペクション時間',
                soundEnabled: 'サウンド有効',
                pressSpace: 'プレス',
                pressSpace2: 'スペースでスタート/停止',
                pressEnter: '新しいスクランブル',
                controls: 'コントロール',
                sessionStats: '統計',
                bluetoothCube: 'Bluetoothキューーブ',
                coachDashboard: 'コーチダッシュボード',
                cfopAnalysis: 'CFOP分析',
                lastSolveDetails: '前回解法詳細',
                solveHistory: '解法履歴',
                scanForCubes: 'キューブをスキャン',
                inspectionSec: 'インスペクション時間（秒）',
                timerSound: 'タイマーサウンド',
                time: '時間',
                scramble: 'スクランブル',
                penalty: 'ペナルティ',
                date: '日付',
                solves: '解法数',
                totalOStepTime: 'Oステップ合計時間',
                crossSolution: 'クロスソリューション',
                f2lPairsInserted: 'F2Lペア挿入',
                totalPStepTime: 'Pステップ合計時間',
                pllCase: 'PLLケース',
                recognitionTime: '認識時間'
            }
        };

        let currentLang = localStorage.getItem('language') || 'en';

        function t(key) {
            return translations[currentLang]?.[key] || translations.en[key] || key;
        }

        function changeLanguage() {
            currentLang = document.getElementById('langSelect').value;
            localStorage.setItem('language', currentLang);
            updateUITexts();
        }

        function updateUITexts() {
            document.querySelectorAll('[data-i18n]').forEach(el => {
                const key = el.getAttribute('data-i18n');
                el.textContent = t(key);
            });
        }

// Expose to window for inline HTML and other modules
window.t = t;
window.changeLanguage = changeLanguage;
window.updateUITexts = updateUITexts;
window.currentLang = currentLang;
window.translations = translations;
